---
title: "MLE ane MM Deliverable MM Part"
author: 'Dong Chen'
date: "10-26"
output:
  html_document:
    code_folding: hide
    number_sections: yes
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r global options, include = FALSE}
knitr::opts_chunk$set(echo=TRUE, warning=FALSE, message=FALSE)
```


```{r}
#Import data
require(dplyr)
Hmisc::getHdata(nhgh)
d1 <- nhgh %>% 
  filter(sex == "female") %>% 
  filter(age >= 18) %>% 
  select(gh, ht) %>% 
  filter(1:n()<=1000)
```

# Normal

```{r}
mm.mean=mean(d1$ht)
mm.sd=sd(d1$ht)
```


```{r}
hist(d1$ht,breaks = 100,freq = F)
curve(dnorm(x,mm.mean,mm.sd),col="red",lwd=6,add=T)
```


```{r}
plot(ecdf(d1$ht))
curve(pnorm(x,mm.mean,mm.sd),col="red",lwd=6,add=T)
```

```{r}
qs <- seq(0.05,0.95,length=50)
sample_qs <- quantile(d1$ht,qs)
theor_qs <- qnorm(qs,mm.mean,mm.sd)
plot(sample_qs,theor_qs,pch=16)
abline(0,1)
```

```{r}
qnorm(0.5,mean=mm.mean,sd=mm.sd)
```


```{r}
M <- 5000
N <- 1000
out <- rnorm(M*N,mean=mm.mean,sd=mm.sd) %>% array( dim=c(M,N))
sample_dist <- apply(out,1,median)
hist(sample_dist, breaks = 100)
```

```{r}
quantile(sample_dist,c(0.05/2, 1 - 0.05/2))
```

# Gamma

```{r}
mm_shape_gamma=mean(d1$ht)^2/var(d1$ht)
mm_scale_gamma=var(d1$ht)/mean(d1$ht)
```


```{r}
hist(d1$ht,breaks = 100,freq = F)
curve(dgamma(x,shape=mm_shape_gamma,scale=mm_scale_gamma),col="red",lwd=6,add=T)
```


```{r}
plot(ecdf(d1$ht))
curve(pgamma(x,shape=mm_shape_gamma,scale=mm_scale_gamma),col="red",lwd=6,add=T)
```

```{r}
qs <- seq(0.05,0.95,length=50)
sample_qs <- quantile(d1$ht,qs)
theor_qs <- qgamma(qs,shape=mm_shape_gamma,scale=mm_scale_gamma)
plot(sample_qs,theor_qs,pch=16)
abline(0,1)
```

```{r}
qgamma(0.5,shape=mm_shape_gamma,scale=mm_scale_gamma)
```


```{r}
M <- 5000
N <- 1000
out <- rgamma(M*N,shape=mm_shape_gamma,scale=mm_scale_gamma) %>% array( dim=c(M,N))
sample_dist <- apply(out,1,median)
hist(sample_dist, breaks = 100)
```

```{r}
quantile(sample_dist,c(0.05/2, 1 - 0.05/2))
```

# Weibull

```{r}
mean.weib = function(lambda,k){
  lambda*gamma(1+1/k)
}

var.weib = function(lambda,k){
  lambda^2*(gamma(1+2/k)-(gamma(1+1/k))^2)
}

lambda = function(samp_mean,k){
  samp_mean/gamma(1+1/k)
}

var.weib = function(samp_mean,k){
  lambda(samp_mean,k)^2*(gamma(1+2/k)-(gamma(1+1/k))^2)
}

var.weib = function(samp_mean,k,samp_var){
  lambda(samp_mean,k)^2*(gamma(1+2/k)-(gamma(1+1/k))^2)-samp_var
}

mm.opt = optimize(f = function(x){abs(var.weib(k=x,samp_mean = mean(d1$ht),samp_var = var(d1$ht)))},lower=10,upper = 100)

mm.weib.k = mm.opt$min

mm.weib.lambda = lambda(samp_mean = mean(d1$ht),k=mm.weib.k)

```

```{r}
mm.weib.k
mm.weib.lambda
```


```{r}
hist(d1$ht,breaks = 100,freq = F)
curve(dweibull(x,shape=mm.weib.k,scale=mm.weib.lambda),col="red",lwd=6,add=T)
```


```{r}
plot(ecdf(d1$ht))
curve(pweibull(x,shape=mm.weib.k,scale=mm.weib.lambda),col="red",lwd=6,add=T)
```

```{r}
qs <- seq(0.05,0.95,length=50)
sample_qs <- quantile(d1$ht,qs)
theor_qs <- qweibull(qs,shape=mm.weib.k,scale=mm.weib.lambda)
plot(sample_qs,theor_qs,pch=16)
abline(0,1)
```

```{r}
qweibull(0.5,shape=mm.weib.k,scale=mm.weib.lambda)
```


```{r}
M <- 5000
N <- 1000
out <- rweibull(M*N,shape=mm.weib.k,scale=mm.weib.lambda) %>% array( dim=c(M,N))
sample_dist <- apply(out,1,median)
hist(sample_dist, breaks = 100)
```

```{r}
#hist(sample_dist, breaks = 100)
quantile(sample_dist,c(0.05/2, 1 - 0.05/2))
#abline(v = quantile(sample_dist,c(0.05/2, 1 - 0.05/2)), col = "blue", lty = 2)
```


